"""
Seeded realistic demo data for FusionScope global crisis fusion dashboard.
48 countries with climate and humanitarian risk indicators matching
water stress → migration pressure → food insecurity fusion patterns.
"""

SEED_COUNTRIES = [
    # East Africa - Extreme Crisis Zone
    {
        "code": "SOM",
        "name": "Somalia",
        "region": "East Africa",
        "lat": 5.15,
        "lon": 46.2,
        "water_stress": 92,
        "drought": 88,
        "flood": 45,
        "food_insecurity": 95,
        "migration_pressure": 87,
        "infrastructure_disruption": 82,
        "summary": "Somalia faces a critical convergence of climate and humanitarian stressors. Multiple risk vectors are operating at extreme levels, creating compounding instability across water, food, and displacement systems. Immediate international coordination is required to prevent cascading failure.",
    },
    {
        "code": "YEM",
        "name": "Yemen",
        "region": "Middle East",
        "lat": 15.55,
        "lon": 48.52,
        "water_stress": 95,
        "drought": 78,
        "flood": 35,
        "food_insecurity": 91,
        "migration_pressure": 72,
        "infrastructure_disruption": 88,
        "summary": "Yemen is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "SSD",
        "name": "South Sudan",
        "region": "East Africa",
        "lat": 6.88,
        "lon": 31.6,
        "water_stress": 85,
        "drought": 82,
        "flood": 72,
        "food_insecurity": 89,
        "migration_pressure": 91,
        "infrastructure_disruption": 78,
        "summary": "South Sudan faces a critical convergence of climate and humanitarian stressors. Multiple risk vectors are operating at extreme levels, creating compounding instability across water, food, and displacement systems. Immediate international coordination is required to prevent cascading failure.",
    },
    {
        "code": "AFG",
        "name": "Afghanistan",
        "region": "South Asia",
        "lat": 33.94,
        "lon": 67.71,
        "water_stress": 88,
        "drought": 85,
        "flood": 62,
        "food_insecurity": 82,
        "migration_pressure": 78,
        "infrastructure_disruption": 91,
        "summary": "Afghanistan is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "ETH",
        "name": "Ethiopia",
        "region": "East Africa",
        "lat": 9.15,
        "lon": 40.49,
        "water_stress": 78,
        "drought": 82,
        "flood": 55,
        "food_insecurity": 75,
        "migration_pressure": 68,
        "infrastructure_disruption": 62,
        "summary": "Ethiopia shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "SDN",
        "name": "Sudan",
        "region": "North Africa",
        "lat": 12.86,
        "lon": 30.22,
        "water_stress": 82,
        "drought": 79,
        "flood": 68,
        "food_insecurity": 85,
        "migration_pressure": 88,
        "infrastructure_disruption": 85,
        "summary": "Sudan is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "SYR",
        "name": "Syria",
        "region": "Middle East",
        "lat": 34.8,
        "lon": 38.99,
        "water_stress": 75,
        "drought": 68,
        "flood": 42,
        "food_insecurity": 72,
        "migration_pressure": 65,
        "infrastructure_disruption": 92,
        "summary": "Syria is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "PAK",
        "name": "Pakistan",
        "region": "South Asia",
        "lat": 30.38,
        "lon": 69.35,
        "water_stress": 72,
        "drought": 58,
        "flood": 88,
        "food_insecurity": 65,
        "migration_pressure": 55,
        "infrastructure_disruption": 72,
        "summary": "Pakistan shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "NGA",
        "name": "Nigeria",
        "region": "West Africa",
        "lat": 9.08,
        "lon": 7.49,
        "water_stress": 65,
        "drought": 58,
        "flood": 72,
        "food_insecurity": 68,
        "migration_pressure": 62,
        "infrastructure_disruption": 55,
        "summary": "Nigeria shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "BGD",
        "name": "Bangladesh",
        "region": "South Asia",
        "lat": 23.68,
        "lon": 90.36,
        "water_stress": 58,
        "drought": 42,
        "flood": 92,
        "food_insecurity": 55,
        "migration_pressure": 48,
        "infrastructure_disruption": 68,
        "summary": "Bangladesh shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    # Additional High-Risk Countries
    {
        "code": "MLI",
        "name": "Mali",
        "region": "West Africa",
        "lat": 17.57,
        "lon": -4.0,
        "water_stress": 78,
        "drought": 82,
        "flood": 38,
        "food_insecurity": 72,
        "migration_pressure": 65,
        "infrastructure_disruption": 58,
        "summary": "Mali is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "TCD",
        "name": "Chad",
        "region": "Central Africa",
        "lat": 15.45,
        "lon": 18.73,
        "water_stress": 85,
        "drought": 78,
        "flood": 42,
        "food_insecurity": 82,
        "migration_pressure": 58,
        "infrastructure_disruption": 72,
        "summary": "Chad is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "MMR",
        "name": "Myanmar",
        "region": "Southeast Asia",
        "lat": 21.91,
        "lon": 95.96,
        "water_stress": 52,
        "drought": 45,
        "flood": 78,
        "food_insecurity": 62,
        "migration_pressure": 72,
        "infrastructure_disruption": 68,
        "summary": "Myanmar shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "MOZ",
        "name": "Mozambique",
        "region": "Southern Africa",
        "lat": -18.67,
        "lon": 35.53,
        "water_stress": 62,
        "drought": 55,
        "flood": 82,
        "food_insecurity": 68,
        "migration_pressure": 45,
        "infrastructure_disruption": 72,
        "summary": "Mozambique shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "HTI",
        "name": "Haiti",
        "region": "Caribbean",
        "lat": 18.97,
        "lon": -72.29,
        "water_stress": 68,
        "drought": 52,
        "flood": 75,
        "food_insecurity": 78,
        "migration_pressure": 72,
        "infrastructure_disruption": 85,
        "summary": "Haiti is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "IRQ",
        "name": "Iraq",
        "region": "Middle East",
        "lat": 33.22,
        "lon": 43.68,
        "water_stress": 82,
        "drought": 72,
        "flood": 48,
        "food_insecurity": 55,
        "migration_pressure": 52,
        "infrastructure_disruption": 65,
        "summary": "Iraq is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "MDG",
        "name": "Madagascar",
        "region": "East Africa",
        "lat": -18.77,
        "lon": 46.87,
        "water_stress": 55,
        "drought": 68,
        "flood": 72,
        "food_insecurity": 75,
        "migration_pressure": 32,
        "infrastructure_disruption": 62,
        "summary": "Madagascar shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "NER",
        "name": "Niger",
        "region": "West Africa",
        "lat": 17.61,
        "lon": 8.08,
        "water_stress": 88,
        "drought": 85,
        "flood": 35,
        "food_insecurity": 78,
        "migration_pressure": 55,
        "infrastructure_disruption": 52,
        "summary": "Niger is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "BFA",
        "name": "Burkina Faso",
        "region": "West Africa",
        "lat": 12.24,
        "lon": -1.56,
        "water_stress": 72,
        "drought": 75,
        "flood": 42,
        "food_insecurity": 68,
        "migration_pressure": 72,
        "infrastructure_disruption": 62,
        "summary": "Burkina Faso is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "COD",
        "name": "DR Congo",
        "region": "Central Africa",
        "lat": -4.04,
        "lon": 21.76,
        "water_stress": 48,
        "drought": 42,
        "flood": 65,
        "food_insecurity": 72,
        "migration_pressure": 78,
        "infrastructure_disruption": 75,
        "summary": "DR Congo is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "LBY",
        "name": "Libya",
        "region": "North Africa",
        "lat": 26.34,
        "lon": 17.23,
        "water_stress": 85,
        "drought": 72,
        "flood": 28,
        "food_insecurity": 48,
        "migration_pressure": 62,
        "infrastructure_disruption": 78,
        "summary": "Libya is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "VEN",
        "name": "Venezuela",
        "region": "South America",
        "lat": 6.42,
        "lon": -66.59,
        "water_stress": 45,
        "drought": 38,
        "flood": 52,
        "food_insecurity": 72,
        "migration_pressure": 82,
        "infrastructure_disruption": 68,
        "summary": "Venezuela shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    # Moderate-Risk Countries
    {
        "code": "CMR",
        "name": "Cameroon",
        "region": "Central Africa",
        "lat": 7.37,
        "lon": 12.35,
        "water_stress": 52,
        "drought": 48,
        "flood": 62,
        "food_insecurity": 58,
        "migration_pressure": 55,
        "infrastructure_disruption": 48,
        "summary": "Cameroon maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "KEN",
        "name": "Kenya",
        "region": "East Africa",
        "lat": -0.02,
        "lon": 37.91,
        "water_stress": 68,
        "drought": 72,
        "flood": 55,
        "food_insecurity": 58,
        "migration_pressure": 42,
        "infrastructure_disruption": 45,
        "summary": "Kenya shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "UGA",
        "name": "Uganda",
        "region": "East Africa",
        "lat": 1.37,
        "lon": 32.29,
        "water_stress": 52,
        "drought": 48,
        "flood": 58,
        "food_insecurity": 55,
        "migration_pressure": 62,
        "infrastructure_disruption": 42,
        "summary": "Uganda maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "ZWE",
        "name": "Zimbabwe",
        "region": "Southern Africa",
        "lat": -19.02,
        "lon": 29.15,
        "water_stress": 72,
        "drought": 68,
        "flood": 42,
        "food_insecurity": 75,
        "migration_pressure": 55,
        "infrastructure_disruption": 62,
        "summary": "Zimbabwe shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "LKA",
        "name": "Sri Lanka",
        "region": "South Asia",
        "lat": 7.87,
        "lon": 80.77,
        "water_stress": 48,
        "drought": 42,
        "flood": 65,
        "food_insecurity": 52,
        "migration_pressure": 38,
        "infrastructure_disruption": 45,
        "summary": "Sri Lanka maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "GTM",
        "name": "Guatemala",
        "region": "Central America",
        "lat": 15.78,
        "lon": -90.23,
        "water_stress": 52,
        "drought": 58,
        "flood": 62,
        "food_insecurity": 55,
        "migration_pressure": 68,
        "infrastructure_disruption": 42,
        "summary": "Guatemala shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "HND",
        "name": "Honduras",
        "region": "Central America",
        "lat": 15.2,
        "lon": -86.24,
        "water_stress": 48,
        "drought": 52,
        "flood": 72,
        "food_insecurity": 52,
        "migration_pressure": 65,
        "infrastructure_disruption": 55,
        "summary": "Honduras shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "EGY",
        "name": "Egypt",
        "region": "North Africa",
        "lat": 26.82,
        "lon": 30.8,
        "water_stress": 78,
        "drought": 62,
        "flood": 32,
        "food_insecurity": 48,
        "migration_pressure": 35,
        "infrastructure_disruption": 38,
        "summary": "Egypt shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "JOR",
        "name": "Jordan",
        "region": "Middle East",
        "lat": 30.59,
        "lon": 36.24,
        "water_stress": 92,
        "drought": 65,
        "flood": 22,
        "food_insecurity": 38,
        "migration_pressure": 55,
        "infrastructure_disruption": 32,
        "summary": "Jordan is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    # Stable Countries for Comparison
    {
        "code": "TUN",
        "name": "Tunisia",
        "region": "North Africa",
        "lat": 33.89,
        "lon": 9.54,
        "water_stress": 72,
        "drought": 58,
        "flood": 35,
        "food_insecurity": 35,
        "migration_pressure": 42,
        "infrastructure_disruption": 28,
        "summary": "Tunisia maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "IND",
        "name": "India",
        "region": "South Asia",
        "lat": 20.59,
        "lon": 78.96,
        "water_stress": 68,
        "drought": 55,
        "flood": 72,
        "food_insecurity": 42,
        "migration_pressure": 32,
        "infrastructure_disruption": 45,
        "summary": "India shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "PHL",
        "name": "Philippines",
        "region": "Southeast Asia",
        "lat": 12.88,
        "lon": 121.77,
        "water_stress": 42,
        "drought": 35,
        "flood": 82,
        "food_insecurity": 38,
        "migration_pressure": 28,
        "infrastructure_disruption": 55,
        "summary": "Philippines shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "IDN",
        "name": "Indonesia",
        "region": "Southeast Asia",
        "lat": -0.79,
        "lon": 113.92,
        "water_stress": 45,
        "drought": 38,
        "flood": 75,
        "food_insecurity": 32,
        "migration_pressure": 25,
        "infrastructure_disruption": 48,
        "summary": "Indonesia maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "COL",
        "name": "Colombia",
        "region": "South America",
        "lat": 4.57,
        "lon": -74.3,
        "water_stress": 38,
        "drought": 35,
        "flood": 62,
        "food_insecurity": 35,
        "migration_pressure": 55,
        "infrastructure_disruption": 42,
        "summary": "Colombia maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "UKR",
        "name": "Ukraine",
        "region": "Europe",
        "lat": 48.38,
        "lon": 31.17,
        "water_stress": 42,
        "drought": 38,
        "flood": 35,
        "food_insecurity": 45,
        "migration_pressure": 72,
        "infrastructure_disruption": 85,
        "summary": "Ukraine is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "MRT",
        "name": "Mauritania",
        "region": "West Africa",
        "lat": 21.01,
        "lon": -10.94,
        "water_stress": 82,
        "drought": 78,
        "flood": 28,
        "food_insecurity": 62,
        "migration_pressure": 42,
        "infrastructure_disruption": 48,
        "summary": "Mauritania is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "NPL",
        "name": "Nepal",
        "region": "South Asia",
        "lat": 28.39,
        "lon": 84.12,
        "water_stress": 45,
        "drought": 42,
        "flood": 72,
        "food_insecurity": 48,
        "migration_pressure": 38,
        "infrastructure_disruption": 52,
        "summary": "Nepal shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "TZA",
        "name": "Tanzania",
        "region": "East Africa",
        "lat": -6.37,
        "lon": 34.89,
        "water_stress": 55,
        "drought": 52,
        "flood": 48,
        "food_insecurity": 52,
        "migration_pressure": 35,
        "infrastructure_disruption": 38,
        "summary": "Tanzania maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "MWI",
        "name": "Malawi",
        "region": "Southern Africa",
        "lat": -13.25,
        "lon": 34.3,
        "water_stress": 58,
        "drought": 62,
        "flood": 68,
        "food_insecurity": 72,
        "migration_pressure": 28,
        "infrastructure_disruption": 55,
        "summary": "Malawi shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "SEN",
        "name": "Senegal",
        "region": "West Africa",
        "lat": 14.5,
        "lon": -14.45,
        "water_stress": 62,
        "drought": 55,
        "flood": 42,
        "food_insecurity": 42,
        "migration_pressure": 48,
        "infrastructure_disruption": 35,
        "summary": "Senegal maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "DJI",
        "name": "Djibouti",
        "region": "East Africa",
        "lat": 11.59,
        "lon": 43.15,
        "water_stress": 88,
        "drought": 82,
        "flood": 32,
        "food_insecurity": 58,
        "migration_pressure": 55,
        "infrastructure_disruption": 45,
        "summary": "Djibouti is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "ERI",
        "name": "Eritrea",
        "region": "East Africa",
        "lat": 15.18,
        "lon": 39.78,
        "water_stress": 78,
        "drought": 75,
        "flood": 28,
        "food_insecurity": 68,
        "migration_pressure": 72,
        "infrastructure_disruption": 65,
        "summary": "Eritrea is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "CAF",
        "name": "Central African Republic",
        "region": "Central Africa",
        "lat": 6.61,
        "lon": 20.94,
        "water_stress": 52,
        "drought": 48,
        "flood": 55,
        "food_insecurity": 78,
        "migration_pressure": 75,
        "infrastructure_disruption": 82,
        "summary": "Central African Republic is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "LBN",
        "name": "Lebanon",
        "region": "Middle East",
        "lat": 33.85,
        "lon": 35.86,
        "water_stress": 62,
        "drought": 45,
        "flood": 38,
        "food_insecurity": 55,
        "migration_pressure": 58,
        "infrastructure_disruption": 72,
        "summary": "Lebanon is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
    {
        "code": "AGO",
        "name": "Angola",
        "region": "Southern Africa",
        "lat": -11.2,
        "lon": 17.87,
        "water_stress": 55,
        "drought": 52,
        "flood": 48,
        "food_insecurity": 55,
        "migration_pressure": 32,
        "infrastructure_disruption": 45,
        "summary": "Angola maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "PRY",
        "name": "Paraguay",
        "region": "South America",
        "lat": -23.44,
        "lon": -58.44,
        "water_stress": 42,
        "drought": 48,
        "flood": 55,
        "food_insecurity": 32,
        "migration_pressure": 22,
        "infrastructure_disruption": 35,
        "summary": "Paraguay maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    # Additional countries to reach 48
    {
        "code": "RUS",
        "name": "Russia",
        "region": "Europe/Asia",
        "lat": 61.52,
        "lon": 105.32,
        "water_stress": 45,
        "drought": 38,
        "flood": 42,
        "food_insecurity": 32,
        "migration_pressure": 28,
        "infrastructure_disruption": 35,
        "summary": "Russia maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "TUR",
        "name": "Turkey",
        "region": "Middle East/Europe",
        "lat": 38.96,
        "lon": 35.24,
        "water_stress": 68,
        "drought": 52,
        "flood": 38,
        "food_insecurity": 42,
        "migration_pressure": 45,
        "infrastructure_disruption": 42,
        "summary": "Turkey shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "GRC",
        "name": "Greece",
        "region": "Europe",
        "lat": 39.07,
        "lon": 21.82,
        "water_stress": 55,
        "drought": 62,
        "flood": 32,
        "food_insecurity": 28,
        "migration_pressure": 32,
        "infrastructure_disruption": 38,
        "summary": "Greece maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "ITA",
        "name": "Italy",
        "region": "Europe",
        "lat": 41.87,
        "lon": 12.57,
        "water_stress": 52,
        "drought": 58,
        "flood": 38,
        "food_insecurity": 25,
        "migration_pressure": 28,
        "infrastructure_disruption": 32,
        "summary": "Italy maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "ESP",
        "name": "Spain",
        "region": "Europe",
        "lat": 40.46,
        "lon": -3.75,
        "water_stress": 62,
        "drought": 68,
        "flood": 32,
        "food_insecurity": 22,
        "migration_pressure": 25,
        "infrastructure_disruption": 28,
        "summary": "Spain shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "DEU",
        "name": "Germany",
        "region": "Europe",
        "lat": 51.17,
        "lon": 10.45,
        "water_stress": 42,
        "drought": 45,
        "flood": 42,
        "food_insecurity": 18,
        "migration_pressure": 22,
        "infrastructure_disruption": 25,
        "summary": "Germany maintains relatively stable conditions across monitored risk domains. Current indicators are within manageable thresholds, though localized vulnerabilities may emerge during seasonal stress periods.",
    },
    {
        "code": "USA",
        "name": "United States",
        "region": "North America",
        "lat": 37.09,
        "lon": -95.71,
        "water_stress": 55,
        "drought": 62,
        "flood": 52,
        "food_insecurity": 28,
        "migration_pressure": 18,
        "infrastructure_disruption": 32,
        "summary": "United States shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "MEX",
        "name": "Mexico",
        "region": "North America",
        "lat": 23.63,
        "lon": -102.55,
        "water_stress": 72,
        "drought": 68,
        "flood": 45,
        "food_insecurity": 52,
        "migration_pressure": 65,
        "infrastructure_disruption": 42,
        "summary": "Mexico shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "BRA",
        "name": "Brazil",
        "region": "South America",
        "lat": -14.24,
        "lon": -51.93,
        "water_stress": 48,
        "drought": 52,
        "flood": 62,
        "food_insecurity": 38,
        "migration_pressure": 32,
        "infrastructure_disruption": 35,
        "summary": "Brazil shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "PER",
        "name": "Peru",
        "region": "South America",
        "lat": -9.19,
        "lon": -75.02,
        "water_stress": 58,
        "drought": 55,
        "flood": 68,
        "food_insecurity": 52,
        "migration_pressure": 42,
        "infrastructure_disruption": 42,
        "summary": "Peru shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "CHN",
        "name": "China",
        "region": "East Asia",
        "lat": 35.86,
        "lon": 104.20,
        "water_stress": 72,
        "drought": 65,
        "flood": 68,
        "food_insecurity": 35,
        "migration_pressure": 28,
        "infrastructure_disruption": 38,
        "summary": "China shows moderate but concerning risk indicators across several domains. While not yet critical, trend analysis suggests potential escalation if climate conditions deteriorate further. Continued surveillance advised.",
    },
    {
        "code": "AUS",
        "name": "Australia",
        "region": "Oceania",
        "lat": -25.27,
        "lon": 133.78,
        "water_stress": 68,
        "drought": 72,
        "flood": 58,
        "food_insecurity": 32,
        "migration_pressure": 15,
        "infrastructure_disruption": 28,
        "summary": "Australia is experiencing significant multi-domain stress with elevated risk of systemic deterioration. Key indicators suggest accelerating pressure on food systems and population stability. Enhanced monitoring and preemptive intervention is recommended.",
    },
]
